### PR TITLE
Update stylesheet.css

### PR DESCRIPTION
**Pull request by reliq**
A more subtle, sleek look.

### CODE REVIEW

**Comment by pdcurtis** [comment]
Many thanks for the input, I will have a look at it shortly and see what I think. 
The styling approach is common to several of the applets and they are intended to be used together so I will need to look into overall changes - possibly a configuration choice of a custom style sheet. 
Several of my applets do already offer access to the style sheets in an editor so users can make changes to match the over theme they use - I use Void hence the rounded corners.

**Comment by reliq** [comment]
Alright. Thanks for considering my change. Well appreciated.

**Comment by pdcurtis** [comment]
@ReliQ  I have had a closer look and the changes are not an improvement for light themes such as the Void theme I use so I have not merged it in.
You do however raise a very valid issue about the need to be able to optimize the applet for different users and themes and I have added the ability for the user to edit the stylesheet from within the applet from the context menu.
The new version is pushed to the repository but not yet on the cinnamon spices web site as I like to test locally for a few days.
I am also looking for a mechanism to preserve the changes a user may make through minor updates to the applet and possibly harmonize changes within the family of applets.
 Thank you again for your input.

**Comment by reliq** [comment]
Alright cool. You're welcome.

**Pull request closed without merging**
